import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jory Shilmover</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sideBySide}>
          <div className={styles.selfImage}>
            <Image src="/images/headshot.jpg" fill alt="" />
          </div>
          <section className={styles.aboutMe}>
            <p>
              Hi, my name is Jory Shilmover and I am currently working full time
              as an iOS developer for BidPro while I finish my AA in Software
              Development from Spokane Community College.
            </p>
            <p>
              Throughout my professional and academic career I have developed a
              wide range of skills in Full-Stack, iOS, and Android development.
              For Android I have learned to use Kotlin to develop native code,
              whilst for iOS this includes the use of Swift, Storyboard, and
              SwiftUI. I am also proficient in development using React, NextJS,
              Angular, node, SQL Server, MongoDB, and PHP.
            </p>
            <p>
              In my free time I enjoy spending time with my family, playing
              video games, and doing projects around the house. As an employee I
              am motivated and enjoy pushing myself to learn new and challenging
              ways of doing things.
            </p>
          </section>
        </div>
        <hr />
        <div className={styles.sideBySide}>
          <div className={styles.halfColumn}>
            <div className={styles.title}>Education</div>
            <section className={styles.bodyText}>
              <div>Associate in Applied Science - Software Development</div>
              <div className={styles.extraInfo}>
                Spokane Community College - June 2023
              </div>
            </section>
          </div>
          <div className={styles.halfColumn}>
            <div className={styles.title}>Certificates</div>
            <section className={styles.bodyText}>
              <div>Certificate - Computer Science</div>
              <div className={styles.extraInfo}>Spokane Community College</div>
              <div>Certificate - Frontend Developer</div>
              <div className={styles.extraInfo}>Spokane Community College</div>
              <div>Certificate - Full-Stack Developer</div>
              <div className={styles.extraInfo}>Spokane Community College</div>
              <div>Certificate - Mobile Developer</div>
              <div className={styles.extraInfo}>Spokane Community College</div>
              <div>Certificate - PHP Developer</div>
              <div className={styles.extraInfo}>Spokane Community College</div>
            </section>
          </div>
        </div>
      </main>
    </>
  );
}
